### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by meck-gd** [edeca/python-quicklz#1]
Hi, nice port!

I encountered a small bug while trying to decompress a malware payload.
https://github.com/edeca/python-quicklz/blob/bb8e9cafa92ffb43f33cba655816318c0ae773f3/quicklz.py#L160
This line is missing an assignment operator. Other than that the logic seems to be working fine :+1:

**Comment by edeca** [comment]
Thanks @heck-gd - I fixed this. It would be great to have some test cases for this module. 

If you can share the input data that triggers this code path that would be helpful.

**Comment by meck-gd** [comment]
@edeca Sure, here's the input data for the code path as base64: https://gist.github.com/heck-gd/6ea348eeb243f0a42d58bc8370316cec
